### ISSUE TITLE
Patch 7405 not recognized as installed

### ISSUE THREAD

**Issue by peterjaap** [Hypernode/hypernode-magerun#10]
This is because $this->appliedPatches returns this;

```
Array
(
   [SUPEE-7405-CE-1-9-2-2] => 1
)
```

While we do an isset check on 'SUPEE-7405' (see https://github.com/Hypernode/hypernode-magerun/blob/master/src/Hypernode/Magento/Command/System/Info/PatchesCommand.php#L81).

We need to strip off the version number using by for example stripping anything after SUPEE-%d.

**Comment by peterjaap** [comment]
This also happens for APPSEC's that have different SUPEE numbers for different Magento versions.

**Comment by peterjaap** [comment]
Moved this problem to https://github.com/Hypernode/tools.hypernode.com/issues/3 since it's better to take care of it at the tools.hypernode.com level instead of the Magerun command level.

**Comment by gwillem** [comment]
Whoops, I've just added the latest patch revision. Let me know if you think it's still better to ignore patch revisions altogether.

**Comment by peterjaap** [comment]
Leave then in, I'll try to find a way to recognize them. Maybe there is a
unique signature somewhere.
