### ISSUE TITLE
--format option is not supported

### ISSUE THREAD

**Issue by boldhedgehog** [Hypernode/hypernode-magerun#2]
Hi,

I'd like to use JSON output of n98mage-run, but the plugin does not support this:

``` bash
n98-magerun.phar --format=json -- sys:info:patches
```

> [RuntimeException]  
> The "--format" option does not exist.  
> sys:info:patches

**Comment by JeroenBoersma** [comment]
I'm on it

**Comment by JeroenBoersma** [comment]
#4

**Comment by boldhedgehog** [comment]
Is there a cache for n98mage-run? I still see the error message.

**Comment by JeroenBoersma** [comment]
You should update the module locally

`cd ~/.n98-magerun/modules/hypernode-magerun`
`git pull`

**Comment by boldhedgehog** [comment]
Of course I did.
Still no luck.

**Comment by JeroenBoersma** [comment]
aah, sorry, Now I see... Wrong function is resolved, mistaken by misreading, will reopen and report when the new version is there

**Comment by boldhedgehog** [comment]
Cool, I started to worry that was something wrong with me.

**Comment by JeroenBoersma** [comment]
So, here you have it #5
