### ISSUE TITLE
Patch 9767 not in Patches list?

### ISSUE THREAD

**Issue by kkrieger85** [Hypernode/hypernode-magerun#45]
It seems that SUPEE-9767 is not listed in HYPERNODE_PATCH_TOOL_URL.

**Comment by peterjaap** [comment]
Actually this is an issue for https://github.com/Hypernode/tools.hypernode.com/ since that's the underlying API. This is merely the magerun command to access it. I've opened the issue there; https://github.com/Hypernode/tools.hypernode.com/issues/6
