### ISSUE TITLE
Patch applied says "No" while they are applied and present in app/etc/applied.patches.list

### ISSUE THREAD

**Issue by 7ochem** [Hypernode/hypernode-magerun#46]
I'm running `hypernode:patches:list` on a CE 1.7.0.2 store with most patches applied but some are missing. The output that the command is giving is wrong though.

This is the output:

![m1 7 0 2-ce-hypernode-patches-list-output](https://user-images.githubusercontent.com/2794908/27075154-7965bb76-5029-11e7-9d39-abd2e913cbea.png)

While the headers in the app/etc/applied.patches.list are these:

![m1 7 0 2-ce-applied-patches-list-headers](https://user-images.githubusercontent.com/2794908/27075375-34efe72c-502a-11e7-9101-c68ce754327f.png)

The command is taking a list from `https://tools.hypernode.com/patches/community/1.7.0.2` which looks like this:

    {
        required: [
            "SUPEE-1533",
            "SUPEE-5344",
            "SUPEE-5994",
            "SUPEE-6285",
            "SUPEE-6482",
            "SUPEE-6788",
            "SUPEE-7405",
            "SUPEE-7405 v1.1",
            "SUPEE-8788",
            "SUPEE-8788 v2",
            "SUPEE-9652"
        ]
    }

This is being compared to the second column (split by `|`) of the `applies.patches.list`. Now this second column isn't consequent in its naming. Additionally the version is not (necessarily) in te second column, but it is in the fourth column.

I'd suggest to reformat the second column value to something you can work with and compare the version part with the fourth column. This way you will get a more precise output of the list.

Additionally I find here:

- Patch SUPEE-5345 was applied. When selecting SUPEE-5344 for 1.7.0.2, you will get a patch named SUPEE-5345
- SUPEE-9767 is not yet in the list (released 2 weeks ago)

**Comment by peterjaap** [comment]
Yes, we know. So far, we've decided to keep it this way due to its inconsistent naming, see this comment; https://github.com/Hypernode/tools.hypernode.com/issues/3#issuecomment-256287485

We are open to PR's though.

Regarding 9767, see https://github.com/Hypernode/tools.hypernode.com/issues/6. This is an issue with the API, not with the magerun command.

**Comment by 7ochem** [comment]
Hi @peterjaap, thanks for your comments. I see now that missing/wrong suggestions should be fixed in the API yes.

Though, the issue you are referencing is not about the inconsistent notation in the `applied.patches.list` more about different numbers for the same security issue and patches that inherit other patches etc.

My issue is with the tool trying to match against the second column of the `applied.patches.list`, which is not in a consistent format by Magento.

PR is on its way... ;)
