### ISSUE TITLE
Fatal Error If Module Has No Version

### ISSUE THREAD

**Issue by sprankhub** [Hypernode/hypernode-magerun#68]
If you have a module without a config > modules > Module_Name > version node, an error occurs on the list-updates command:

    > n98-magerun.phar hypernode:modules:list-updates
    PHP Fatal error:  Uncaught Error: Call to a member function descend() on boolean in /home/simon/.n98-magerun/modules/hypernode-magerun/src/Hypernode/Magento/Command/Hypernode/Modules/ListUpdatesCommand.php:205
    Stack trace:
    #0 /home/simon/.n98-magerun/modules/hypernode-magerun/src/Hypernode/Magento/Command/Hypernode/Modules/ListUpdatesCommand.php(95): Hypernode\Magento\Command\Hypernode\Modules\ListUpdatesCommand->getExtensionVersion('Ugly_ModuleWithoutVersion')
    #1 phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Command/Command.php(264): Hypernode\Magento\Command\Hypernode\Modules\ListUpdatesCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #2 phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(473): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    #3 phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console in /home/simon/.n98-magerun/modules/hypernode-magerun/src/Hypernode/Magento/Command/Hypernode/Modules/ListUpdatesCommand.php on line 205

    Fatal error: Uncaught Error: Call to a member function descend() on boolean in /home/simon/.n98-magerun/modules/hypernode-magerun/src/Hypernode/Magento/Command/Hypernode/Modules/ListUpdatesCommand.php on line 205

    Error: Call to a member function descend() on boolean in /home/simon/.n98-magerun/modules/hypernode-magerun/src/Hypernode/Magento/Command/Hypernode/Modules/ListUpdatesCommand.php on line 205

    Call Stack:
        0.0215    1318616   1. {main}() /usr/local/bin/n98-magerun.phar:0
        0.0301    2519864   2. N98\Magento\Application->run() /usr/local/bin/n98-magerun.phar:22
        0.1370   12043336   3. N98\Magento\Application->run() phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:642
        0.1370   12043336   4. N98\Magento\Application->doRun() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:122
        0.1374   12062544   5. N98\Magento\Application->doRun() phar:///usr/local/bin/n98-magerun.phar/src/N98/Magento/Application.php:610
        0.1375   12128080   6. N98\Magento\Application->doRunCommand() phar:///usr/local/bin/n98-magerun.phar/vendor/symfony/console/Application.php:191

**Comment by sprankhub** [comment]
Thanks a lot for that useful plugin!

**Comment by vdloo** [comment]
hi @sprankhub this should be solved by https://github.com/Hypernode/hypernode-magerun/pull/70
