### ISSUE TITLE
Add --exclude option to sys:info:list-updates

### ISSUE THREAD

**Issue by peterjaap** [Hypernode/hypernode-magerun#7]
Since all extension names are sent to Hypernode over HTTP right now, it would be wise to add an --exclude option for users that don't wish to send their sometimes highly descriptive module names and namespaces data to the Hypernode platform. Add support for a wildcard for easy excluding.

`--exclude MyNamespace_*`

**Comment by erfanimani** [comment]
+1

**Comment by peterjaap** [comment]
Or maybe a whitelist functionality as well, like `--include` that does the reverse

**Comment by erfanimani** [comment]
Another suggestion could be to take the approach that dependency managers take, where the comparison of the versions is done on the client-side instead of the server, which eliminates the need to send a list of all installed modules to the server in the first place.

**Comment by peterjaap** [comment]
Though that would mean that every time somebody would check their versions, the **complete** list of all modules and their versions would be downloaded first. I'm not sure Hypernode/Byte is willing to release that info at all, let alone the extra step of downloading a big file instead of uploading & receiving smaller files.

**Comment by erfanimani** [comment]
Yeah - that's true, I can't see why not though, as it's crowdsourced information anyway afaik, and the list would be a couple MB's max. It works fine for Packagist or NPM even though their JSON blobs are many times larger.

edit: ah, the version information is sourced from Hypernode's hosting platform, so indeed it might not be practical to send the whole thing to the client..

**Comment by peterjaap** [comment]
It's crowdsourced from their own platform, so it's proprietary data as such.

**Comment by JeroenBoersma** [comment]
@peterjaap --include is already implemented with the "vendor" option, likewise the --codepool option so one could only send their community modules.

https is implemented this last weekend by @gwillem

**Comment by peterjaap** [comment]
Ok, closing issue.
