### ISSUE TITLE
Wrong required patches for M1 Community v1.9.1.1

### ISSUE THREAD

**Issue by richardklint** [Hypernode/hypernode-magerun#81]
According to the hypernode website, we need patches 10266 and 10415 however these were replaced with patch 10497 specifically for v1.9.1.1 and was documented here: https://community.magento.com/t5/News-Announcements/Action-required-SUPEE-10497-available-for-users-of-Magento-Open/td-p/81942

Just need someone from hypernode to update the required patches that get returned here: https://tools.hypernode.com/patches/community/1.9.1.1

Thanks

**Comment by vdloo** [comment]
Mmmm, we automatically sync our API from [this spreadsheet maintained by JH](https://docs.google.com/spreadsheets/d/1MTbU9Bq130zrrsJwLIB9d8qnGfYZnkm4jBlfNaBF19M/pubhtml?widget=true) but there is no mention of 10497 there while it was updated more recently than Magento community forums post you linked.
